services:
  - type: web
    name: seengroup-backend
    env: node
    plan: starter
    buildCommand: npm ci --omit=dev && npx prisma generate
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: COMPANY_NAME
        sync: false
      - key: CONTACT_EMAIL
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: TEST_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_PUBLIC_BASE_URL
        sync: false
      - key: S3_FORCE_PATH_STYLE
        value: "true"
      - key: CAPTCHA_ENABLED
        value: "true"
      - key: TURNSTILE_SECRET_KEY
        sync: false
      - key: SKIP_CAPTCHA
        value: "false"
    healthCheckPath: /health
    autoDeploy: true
